[workspace]
resolver = "2"
members = [
    "dartfrog",
    "dartfrog_lib",
    "chat",
    "piano",
    "page",
    "chess",
    "radio",
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
