[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
kinode_process_lib = { git = "https://github.com/kinode-dao/process_lib", rev = "43afdf4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"